name: "Auto-Checkin(glados/ikuuu)"

on:
  schedule:
    - cron: "0 7/12 * * *"  # scheduled at 03:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          # 设置运行脚本的 Python 版本，建议使用稳定版本
          python-version: '3.8'

      - name: Set current date
        id: date
        run: echo "TODAY=$(date -d '+8 hour' +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-50 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download previous checkin status
        uses: actions/download-artifact@v4
        if: ${{ secrets.GH_ACCESS_TOKEN != '' }}
        with:
          name: checkin-status-${{ env.TODAY }}
          path: .
        continue-on-error: true # 如果不存在，依然继续

      - name: Run Checkin
        env:
          # 需要添加Action Secrets
          # 添加Action Secrets的路径如下：Settings -> Security -> Secrets and variables -> Actions -> New repository secrets
          # glados配置，用||隔开
          GR_COOKIE: ${{ secrets.GR_COOKIE }}
          GLADOS_BASE_URL: ${{ secrets.GLADOS_BASE_URL }}
          # ikuuu配置，用||隔开
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          IKUUU_BASE_URL: ${{ secrets.IKUUU_BASE_URL }}
          # 通知配置
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }} # telgram推送，选填
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }} # telgram推送，选填
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }} # serverchan推送，选填
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }} # pushplus推送，选填
        run: |
          python3 ./main.py

      - name: Upload current checkin status
        uses: actions/upload-artifact@v4
        if: ${{ secrets.GH_ACCESS_TOKEN != '' }}
        with:
          name: checkin-status-${{ env.TODAY }}
          path: status.json
          retention-days: 1
